# Generated by Django 3.2.10 on 2022-02-03 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_interest_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
