# Generated by Django 4.0 on 2021-12-11 18:02

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('objects', apps.user.models.APIUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_api_user',
            field=models.BooleanField(default=False),
        ),
    ]
