# Generated by Django 4.0 on 2021-12-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_apiuser_user_is_api_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_token_invalidated',
            field=models.BooleanField(default=False),
        ),
    ]
